CREATE TABLE LIVROS(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    COLECAO VARCHAR(255),
    TITULO VARCHAR(255) NOT NULL UNIQUE, 
    AUTOR_ID BIGINT,
    FOREIGN KEY (AUTOR_ID) REFERENCES AUTORES(ID),
    EDITORA VARCHAR(255) NOT NULL, 
    TIPO VARCHAR(255) NOT NULL,
    FORMATO VARCHAR(255) NOT NULL,
    QUANTIDADE_PAGINAS INTEGER NOT NULL, 
    EDICAO INTEGER NOT NULL,
    ANO_EDICAO INTEGER NOT NULL,
    GENEROS VARCHAR(255) NOT NULL,
    ACABAMENTO VARCHAR(255) NOT NULL,
    IDIOMA VARCHAR(255) NOT NULL,
    PAIS VARCHAR(255) NOT NULL,
    QUANTIDADE_LIVROS INTEGER NOT NULL
);
