CREATE TABLE LIVROS(

    ID BIGINT NOT NULL AUTO_INCREMENT,
    COLECAO VARCHAR(100),
    TITULO VARCHAR(300) NOT NULL UNIQUE, 
    AUTOR VARCHAR(100) NOT NULL,
    EDITORA VARCHAR(100) NOT NULL, 
    TIPO VARCHAR(100) NOT NULL,
    FORMATO VARCHAR(100) NOT NULL,
    QUANTIDADE_PAGINAS INTEGER NOT NULL, 
    EDICAO INTEGER NOT NULL,
    ANO_EDICAO INTEGER NOT NULL,
    GENEROS TEXT(1000) ARRAY NOT NULL,
    ACABAMENTO VARCHAR(300) NOT NULL,
    IDIOMA VARCHAR(300) NOT NULL,
    PAIS VARCHAR(300) NOT NULL,
    QUANTIDADE_LIVROS INTEGER NOT NULL,

    PRIMARY KEY(ID)

);
