CREATE TABLE AUTORES(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL UNIQUE,
    NACIONALIDADE VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    DATA_MORTE DATE
);
