CREATE TABLE BOOKS(

    ID BIGINT NOT NULL AUTO_INCREMENT,
    COLLECTION VARCHAR(100),
    TITLE VARCHAR(300) NOT NULL UNIQUE, 
    AUTHOR VARCHAR(100) NOT NULL,
    PUBLISHER VARCHAR(100) NOT NULL, 
    TYPE VARCHAR(100) NOT NULL,
    FORMAT VARCHAR(100) NOT NULL,
    PAGES INTEGER NOT NULL, 
    EDITION INTEGER NOT NULL,
    EDITION_YEAR INTEGER NOT NULL,
    GENRES VARCHAR(300) NOT NULL,
    FINISHING VARCHAR(300) NOT NULL,
    LANGUAGE VARCHAR(300) NOT NULL,
    COUNTRY VARCHAR(300) NOT NULL,
    BOOK_QUANTITY INTEGER NOT NULL,

    PRIMARY KEY(ID)

);
