CREATE TABLE LIVRO_GENERO (
    LIVRO_ID BIGINT NOT NULL,
    GENERO_ID BIGINT NOT NULL,
    PRIMARY KEY (LIVRO_ID, GENERO_ID),
    FOREIGN KEY (LIVRO_ID) REFERENCES LIVROS (ID),
    FOREIGN KEY (GENERO_ID) REFERENCES GENEROS (ID)
);
